### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by bitemyapp** [hvr/cassava#101]
Context: https://mail.haskell.org/pipermail/ghc-devs/2015-October/010139.html

Your work for the Haskell community is much appreciated. I have a particular fondness for Cassava as I discovered it at a time when I was thrashing with Haskell libraries and finding them difficult to use. It was a refreshing respite and the simplicity of the API meant I was able to start processing some CSV data in a jiffy. That was a real joy.

In fact, I used it [in my HowIStart article for the demo project](http://howistart.org/posts/haskell/1), because I was confident new people could deal with how the library works.

If you're not going to maintain your libraries, I'd like to propose myself for maintainership of cassava. We may not agree on everything, but for cassava, I'd take a conservative approach. On the one hand, I'd like to address the backlog of issues and PRs so that improvements are made and concerns are being heard. On the other hand, I'll be strongly opposed to change-for-the-sake-of-change and I _desperately_ want to keep this library a pleasant safe-haven for programmers that just-want-to-parse-some-CSV-data-dammit.

My Hackage account is http://hackage.haskell.org/user/bitemyapp - let me know if you have any questions or if I misunderstood and you'll be maintaining this library.

**Comment by hvr** [comment]
I guess we can close this for now... :-)

Feel free to point my attention to issues that need urgent attention

**Comment by bitemyapp** [comment]
@hvr wfm :+1:
