### ISSUE TITLE
Documentation for Functor instance of Data.Csv.Streaming.Records does not what it says

### ISSUE THREAD

**Issue by romanofski** [hvr/cassava#102]
The documentation of the Functor instance implementation for `Records a` says:

    Skips records that failed to convert.

But the implementation stops the recursion once it hits a Left. If the first record is a Left, but continues with Rights I get nothing. I wonder if either:

1. the documentation is wrong or
1. the implementation is missing a pattern match.

I'd be interested to contribute a pull request with the right fix. For the latter it'll be very cool to give some advice on where to put the test, maybe even with a code example.

Kind Regards

**Comment by tibbe** [comment]
Your fix looks right to me. @hvr wanna merge?

**Comment by hvr** [comment]
@tibbe done; do you consider semantic fixes like these a minor ver bump or rather a major ver bump?

**Comment by tibbe** [comment]
Tricky question. I would call it a patch-level bump given that the implementation didn't match the docs. Now, if lots of people depended on the current behavior (e.g. if we were talking about the Linux kernel) we couldn't do that. So perhaps a minor version bump just to be sure?

**Comment by romanofski** [comment]
Thanks for merging. I'm not sure if you were a bit too quick? I haven't had time to verify, but I have a feeling that the foldl instance is affected by the same bug too. Happy to hack on that fix as well ...

**Comment by hvr** [comment]
@romanofski well, nothing's been released yet... :-)

It'd be great if you could verify the `foldl`, and fix that as well (and submit a new PR)
