### ISSUE TITLE
QuoteMinimal should not quote fields with spaces

### ISSUE THREAD

**Issue by nh2** [hvr/cassava#118]
In `QuoteMinimal` mode, cassava puts fields with spaces (` `) into quotes (`"`). I think this is not correct.

Wikipedia [as of today states](https://en.wikipedia.org/w/index.php?title=Comma-separated_values&oldid=723065927) that

> According to RFC 4180, spaces outside quotes in a field are not allowed

I believe Wikipedia is wrong here. This change to Wikipedia was contributed anonymously [here](https://en.wikipedia.org/w/index.php?title=Comma-separated_values&type=revision&diff=592965137&oldid=592554922) and lacks backup.

[This Stackoverflow answer](http://stackoverflow.com/questions/22492244/is-whitespace-at-the-end-of-a-line-valid-csv) tries to explain this sentence in Wikipedia:

> The relevant part of the grammar looks like:
> 
> record = field *(COMMA field)
> field = (escaped / non-escaped)
> escaped = DQUOTE *(TEXTDATA / COMMA / CR / LF / 2DQUOTE) DQUOTE
> 
> which doesn’t allow for whitespace outside of the quotes in a field.

I believe that this, too, is wrong, as I comment [here](http://stackoverflow.com/questions/22492244/is-whitespace-at-the-end-of-a-line-valid-csv#comment62645138_22514146):

While the person on Stackoverflow references `escaped`, the important bit is

> non-escaped = *TEXTDATA
> TEXTDATA = %x20-21 / %x23-2B / %x2D-7E

In there `%x20` is the space character. So ` `is allowed as`non-escaped`, and thus as`field`and thus need not be quoted, and thus should not be quoted for`QuoteMinimal`.

Excel's CSV exporter agrees with this, so does LibreOffice's. I've also opened a Wikipedia discussion [here](https://en.wikipedia.org/wiki/Talk:Comma-separated_values#Section_about_spaces_potentially_wrong.3F). But I think the RFC grammar supports my analysis.

**Comment by hvr** [comment]
This is related/duplicate to #86
