### ISSUE TITLE
vector v0.12.0.0

### ISSUE THREAD

**Issue by kazu-yamamoto** [hvr/cassava#129]
Please support vector v0.12 and release a new version.

**Comment by crockeea** [comment]
I think this ticket is the only thing preventing me from putting my own package on Stackage, so it'd be great to get this done!

**Comment by crockeea** [comment]
There's a pull request #125 resolves this...all it needs is a merge.

**Comment by sjakobi** [comment]
This was fixed by a trustee: http://hackage.haskell.org/package/cassava-0.4.5.1/revisions/

**Comment by kazu-yamamoto** [comment]
Confirmed. Thanks.

**Comment by hvr** [comment]
resolved by #125
