### ISSUE TITLE
Invalid flag name: "bytestring--lt-0_10_4"

### ISSUE THREAD

**Issue by bwbaugh** [hvr/cassava#150]
While trying to generate a `stack.yaml` for [jtdaugherty/tart](https://github.com/jtdaugherty/tart), I ran into the following error about the `bytestring--lt-0_10_4` flag:

```bash
$ stack init --solver --resolver=nightly
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- tart.cabal

Selected resolver: nightly-2017-08-14
Selected resolver: nightly-2017-08-14
Downloaded nightly-2017-08-14 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

**Comment by hvr** [comment]
I'm afraid I'll have to redirect you to the Stack issue tracker, as this is a bug in Stack. The package works perfectly fine with `cabal` & hackage.

**Comment by johnmendonca** [comment]
`stack upgrade` should fix this
