### ISSUE TITLE
error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.

### ISSUE THREAD

**Issue by RyanGlScott** [hvr/cassava#154]
I recently ran into this issue when installing some packages with `--allow-newer`. One can reproduce the issue by installing `cassava-0.5.1.0` by itself with `--allow-newer` (I'm using `cabal-install-2.0.0.0`, if that makes a difference):

```
$ cabal install cassava --allow-newer
Resolving dependencies...
Configuring cassava-0.5.1.0...
Building cassava-0.5.1.0...
Failed to install cassava-0.5.1.0
Build log ( /u/rgscott/.cabal/logs/ghc-8.2.1/cassava-0.5.1.0-6OWXHnNDaQwGfhEhSLNfq5.log ):
cabal: Entering directory '/tmp/cabal-tmp-444/cassava-0.5.1.0'
Configuring cassava-0.5.1.0...
Preprocessing library for cassava-0.5.1.0..
Building library for cassava-0.5.1.0..

Data/Csv/Conversion.hs:26:3: error:
     error: #error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
     # error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
       ^
   |
26 | # error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
   |   ^

Data/Csv/Conversion.hs:99:0: error:
     warning: "MIN_VERSION_text_short" is not defined [-Wundef]
     #if MIN_VERSION_text_short(0,1,0)
     ^
   |
99 | #if MIN_VERSION_text_short(0,1,0)
   | ^

Data/Csv/Conversion.hs:99:0: error:
     error: missing binary operator before token "("
   |
99 | #if MIN_VERSION_text_short(0,1,0)
   | ^

Data/Csv/Conversion.hs:1010:0: error:
     warning: "MIN_VERSION_text_short" is not defined [-Wundef]
     #if MIN_VERSION_text_short(0,1,0)
     ^
     |
1010 | #if MIN_VERSION_text_short(0,1,0)
     | ^

Data/Csv/Conversion.hs:1010:0: error:
     error: missing binary operator before token "("
     |
1010 | #if MIN_VERSION_text_short(0,1,0)
     | ^
`gcc' failed in phase `C pre-processor'. (Exit code: 1)
cabal: Leaving directory '/tmp/cabal-tmp-444/cassava-0.5.1.0'
cabal: Error: some packages failed to install:
cassava-0.5.1.0-6OWXHnNDaQwGfhEhSLNfq5 failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by hvr** [comment]
@RyanGlScott This isn't actually a bug... that's the very reason I placed that CPP assertion in there ;-)

Fwiw, the unqualified `--allow-newer` sledge-hammer is going to get deprecated or at least emit a big fat warning in future cabals. I've recently invested some time to significantly extend `--allow-{older,newer}` capabilities to allow for fine-grained control, see http://cabal.readthedocs.io/en/latest/nix-local-build.html#cfg-field-allow-newer for current state. TLDR: don't use an unqualified `--allow-newer`, it's almost always *not* what you want.

**Comment by RyanGlScott** [comment]
I'm still confused as to what exactly the problem would be with building `cassava` with the most recent versions of all dependencies.

**Comment by hvr** [comment]
@RyanGlScott the problem is that you end up with a configuration which lacks class instances as the flag logic in the .cabal file which is considered as invariant wouldn't hold up anymore; this is because ignoring all upper bounds also removes bounds whose function is rather as  predicates for the conditionals than dependency bounds. However, with the introduction of `^>=`-style bounds, we finally have a way to distinguish between hard and soft bounds in a more natural way.

**Comment by RyanGlScott** [comment]
That makes sense. Thanks!
