### ISSUE TITLE
`FromField ShortByteString` instance

### ISSUE THREAD

**Issue by hvr** [hvr/cassava#91]
`ShortByteString`s are often desirable for short fields instead of `ByteString`s, so something along the following instance might be desirable:

```haskell
import qualified Data.ByteString.Short as SBS

instance FromField ShortByteString where
    parseField = fmap SBS.toShort . parseField
```

/cc @dcoutts

**Comment by bitemyapp** [comment]
@hvr this is fixed is it not?

**Comment by hvr** [comment]
indeed... was part of the `cassava-0.4.4.0` release afaics
